package com.example

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class GoogleSignInConfigurationTest {

    @Test
    fun verifyDefaultWebClientId_isGeneratedAndValid() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        
        assertTrue("default_web_client_id resource should be generated by google-services plugin", resId != 0)
        
        val webClientId = context.getString(resId)
        assertNotNull(webClientId)
        assertTrue("Web Client ID should not be blank", webClientId.isNotBlank())
        assertTrue("Web Client ID should end with apps.googleusercontent.com", webClientId.endsWith("apps.googleusercontent.com"))
    }
}
